### ISSUE TITLE
Clarify the container running environment about offline and read-only

### ISSUE THREAD

**Issue by mpizenberg** [exercism/generic-test-runner#23]
Back in February, we had an issue for the elm-test-runner related to the fact that the elm compiler is writing a lock file inside `~/.elm/` and that folder used to be read-only (https://github.com/exercism/elm-test-runner/issues/1#issuecomment-578696771).

We were advised to test the container by using `docker run --network none --read-only` inside the `run-in-docker.sh` script. I don't see such options in that script in this template repo. Are those network and read-only requirements been removed since back in February? Having `~/.elm/` being writable in particular would help simplify our `run.sh` script.

**Comment by cmccandless** [comment]
Pinging @ccare

**Comment by neenjaw** [comment]
@cmccandless, @ccare isn't responsible for this any more.  It's now just @iHiD and @ErikSchierboom iirc. 

In regard to the network clarification, this has been patched to the docs with this PR I think: https://github.com/exercism/automated-analysis/pull/107

**Comment by iHiD** [comment]
@mpizenberg The readonly requirement wasn't enforced as it proved too hard for lots of tracks, so hopefully that's easier for you! :) The network is as @neenjaw commented.
