### ISSUE TITLE
First automated PR on newly created jq-test-runner fails

### ISSUE THREAD

**Issue by glennj** [exercism/generic-test-runner#80]
This is https://github.com/exercism/jq-test-runner/pull/1 "Sync org-wide files to upstream repo"

The CI workflow fails: 

- the Dockerfile uses alpine and does not install any extra packages
- the entrypoint calls `run.sh` which includes `jq`.

https://github.com/exercism/jq-test-runner/runs/8211450383?check_suite_focus=true

```none
bin/run.sh: line 56: jq: not found
...
Error: Process completed with exit code 1.
```

@ErikSchierboom @iHiD

**Comment by glennj** [comment]
It seems the straightforward fix is to uncomment this from the [Dockerfile](https://github.com/exercism/generic-test-runner/blob/main/Dockerfile)
```dockerfile
FROM alpine:3.10

# TODO: install packages required to run the tests
# RUN apk add --no-cache jq coreutils
```

**Comment by glennj** [comment]
But digging one shovel-ful deeper, the tests are going to fail (by design) because the run.sh script calls a non existing RUN_TEST_COMMAND.

The real approach is to keep exercism-bot away until the test-runner is declared "active" (somehow).

**Comment by ErikSchierboom** [comment]
@glennj What do you think about enabling `jq` and then commenting `RUN_TEST_COMMAND`?

**Comment by ErikSchierboom** [comment]
What about:

```bash
# Run the tests for the provided implementation file and redirect stdout and
# stderr to capture it
test_output=$(false)
# 
# TODO: substitute "false" with the actual command to run the test:
# test_output=$(command_to_run_tests 2>&1)
```

This is slightly shorter and to me reads a bit better. Thoughts?

**Comment by glennj** [comment]
Yes! Perfect.
